### ISSUE TITLE
Why do we need three "weight_matrices" vectors

### ISSUE THREAD

**Issue by zihaozou** [NVlabs/tiny-cuda-nn#107]
I noticed that when doing forward, backward, and inference, the network will pick different half-precision weight matrix vectors, depending on "WeightUsage". My question is why do need three kinds of weight matrix vectors. Isn't one weight matrix vector enough to do forward, backward, and inference? 
If we have to use three weight matrix vectors, I think there should be some processes to synchronize the data of three matrix vectors(I noticed their data address is assigned differently in the trainer's code). I've been searching for related code, but unfortunately, I couldn't find it. Could you point me out if there is anything wrong with my logic, or help me find the related codes?

**Comment by Tom94** [comment]
Custom weights for inference are used to implement post-processing algorithms on the trained parameters. There exist many -- two ones that are implemented in __tiny-cuda-nn__ in terms of the `Optimizer` interface are [exponential weight averaging](https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage) or [lookahead](https://arxiv.org/abs/1907.08610). Exponential weight averaging is used in __instant-ngp__ applications to suppress flickering caused by training with high learning rates.

Custom weights for the backward pass are used to implement [feedback alignment](https://arxiv.org/abs/1411.0247). This is off by default, though. You can enable it in the json config if you want.

**Comment by zihaozou** [comment]
Thanks for the answer. I just found the related code at [https://github.com/NVlabs/tiny-cuda-nn/blob/ee585fa47e99de4c26f6ae88be7bcb82b9295310/src/fully_fused_mlp.cu#L915](feedback_alignment).
So the forward and backward matrices are set to the same position if feedback alignment is off.
