### ISSUE TITLE
GPU out of memory as training goes on

### ISSUE THREAD

**Issue by CDWJ** [NVlabs/tiny-cuda-nn#166]
Hi there,

I'm running on a RTX8000 GPU and my cuda version is 11.6 with pytorch 1.12 installed.
I have some question about the behavior of my GPU memory allocation plot. I'm trying to do a deep copy of a trained instant-ngp model and continue training it with new input fed in. However, sometimes (with different generated training samples) the GPU memory seems to increase as I fed in more input points and eventually causing an out of memory exception. 
I'm not sure what is causing the problem, is this 1. because of the memory is dynamically allocated when hash collision happens? or 2. the way I do my deep copy which is just `copy.deepcopy(model)` is not the way to deal with tiny cudann model? 

Thanks in advance for any suggestions!

**Comment by Tom94** [comment]
Hi, the deep copy shouldn't allocate any extra memory besides the trainable parameters of the model, which are fixed and don't dynamically grow due to collisions.

That said, __tiny-cuda-nn__ maintains a pool of GPU memory for temporary objects (such as hidden activations), which scales with the batch size that you use.

So, if you experience memory growth only when you increase the number of points you feed to the model at a time, then that's expected (necessary) behavior. You can always free the memory again by calling `tcnn.free_temporary_memory()`, but beware that the same amount of memory will be allocated again once you pass another batch of equal size.

On the other hand, if you experience _indefinite_ growth of the memory usage there's a chance this is a bug and it would be helpful if you could share a minimal example that reproduces the problem.
