### ISSUE TITLE
Error when try to minimize gradient with respective to input in pytorch binding

### ISSUE THREAD

**Issue by thuanz123** [NVlabs/tiny-cuda-nn#176]
Basically, I have a loss as the gradient of the output with respective to the input and I want to minimize it but I encounter this error when trying to do so in pytorch binding:
`RuntimeError: DifferentiableObject::backward_backward_input_impl: not implemented error`

Does this mean the second derivative of fully fused mlp is not implemented in pytorch ?

**Comment by Tom94** [comment]
Hi, second derivatives are not (yet) supported by __tiny-cuda-nn__'s neural networks.

If you're mostly interested in using the hash encoding (which _does_ support second derivatives), you need to compose the hash encoding with PyTorch-side neural network (i.e. use tcnn.Encoding and torch.nn.Linear rather than tcnn.NetworkWithInputEncoding).

More info here: https://github.com/NVlabs/tiny-cuda-nn/issues/131#issuecomment-1210726647

Cheers
