### ISSUE TITLE
pytorch extensions error:_C is not defined

### ISSUE THREAD

**Issue by sadexcavator** [NVlabs/tiny-cuda-nn#202]
hello, when I tried to run a nvdiffrec demo, a error occured, the log I get:
Traceback (most recent call last):
  File "/home/wsr/workspace/nvdiffrec-main/train.py", line 35, in <module>
    from render import mlptexture
  File "/home/wsr/workspace/nvdiffrec-main/render/mlptexture.py", line 11, in <module>
    import tinycudann as tcnn
  File "/home/wsr/anaconda3/envs/dmodel/lib/python3.9/site-packages/tinycudann/__init__.py", line 9, in                           <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/wsr/anaconda3/envs/dmodel/lib/python3.9/site-packages/tinycudann/modules.py", line 33, in                           <module>
    if _C is None:
NameError: name '_C' is not defined
-------------------------------------------------
please tell me how to fix this, I suspect something's wrong with my gcc installation, cause I used to run OK on another server, this time I create a new environment on a new server, then I find the GCC version is 5.x which not meet your requirements, so I installed GCC 9.3.0 in my directory(cause I am not root user), and I configured its correspond path(when I enter gcc -v, the output shows it's gcc 9.3.0) so I believed i've installed it successfully. Because this two environments only differ with this GCC version problem, so I wonder if this caused this error. Anyway I can't seem to fix this. please help me.

**Comment by sadexcavator** [comment]
I solved it by configuring the bashrc

**Comment by Wjt-shift** [comment]
> I solved it by configuring the bashrc

hi,i also meet that problem,how did you solve it?thanks for your help.

**Comment by sadexcavator** [comment]
I just add these at the last of my .bashrc file, you can try, just configure your own gcc related path right
--------------------------
export PATH=/home/wsr/gcc/gcc-9.3.0/bin:$PATH
export LD_LIBRARY_PATH=/home/wsr/gcc/gcc-9.3.0/lib64/:$LD_LIBRARY_PATH
--------------------------
but I don't know if this gonna work for you too, unfortunately even though I solved this one, I've encoutered other new problems during my running.

**Comment by csyhping** [comment]
For those who meet a similar problem, here is how I solved it.

Check your error information, it occurs when try to check the system_compute_capability and load tinycudann_bindings [#L22-34 in modules.py](https://github.com/NVlabs/tiny-cuda-nn/blob/8e6e242f36dd197134c9b9275a8e5108a8e3af78/bindings/torch/tinycudann/modules.py#L22).  The error info means that it failed to load a matched tinycudann_bindings. To solve this, you have to check the compute_capability of your GPU and install a matched `tinycudann` accordingly. 

Explicitly specify `TCNN_CUDA_ARCHITECTURES` as [this answer in #277](https://github.com/NVlabs/tiny-cuda-nn/issues/277#issuecomment-1473297001). 

For my case, I use:
`export TCNN_CUDA_ARCHITECTURES=75 && pip install git+https://github.com/NVlabs/tiny-cuda-nn@v1.6#subdirectory=bindings/torch`

BTW: if you have installed `tinycudann` before, I suggest you uninstall it rather than update it. Otherwise the error may still exist.

Hope this helps.

**Comment by ZJLi2013** [comment]
I am building with Dockerfile, sounds the root cause of this error comes from a conflict definition.

e.g. my local gpu comput_arch is 86, then in `binding/torch/tinycudann/modules.py`,  `_C` is looking for `tinnycudann_bindings_86._C` ,  while with straight forward docker build, it generates `/home/user/.local/lib/python3.10/site-packages/tinnycudann_bindings_37._C` 

as predefined `ARG CUDA_ARCHITECTURES=86;80;75;70;61;52;37` in Dockerfile, 

```py
if "TCNN_CUDA_ARCHITECTURES" in os.environ and os.environ["TCNN_CUDA_ARCHITECTURES"]:
	compute_capabilities = [int(x) for x in os.environ["TCNN_CUDA_ARCHITECTURES"].replace(";", ",").split(",")]
	print(f"Obtained compute capabilities {compute_capabilities} from environment variable TCNN_CUDA_ARCHITECTURES")
elif torch.cuda.is_available():
	major, minor = torch.cuda.get_device_capability()
	compute_capabilities = [major * 10 + minor]
	print(f"Obtained compute capability {compute_capabilities[0]} from PyTorch")
else:
	raise EnvironmentError("Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.")

min_compute_capability = min(compute_capabilities)
...
ext = CUDAExtension(
	name=f"tinycudann_bindings_{min_compute_capability}._C",
	sources=source_files,

```
so here it build out `tinycudann_bindings_37._C` , not compatible with local compute_arch 

my solution here is to rebuild `extension/torch`

```sh
git clone --recursive -b v1.6 https://github.com/NVlabs/tiny-cuda-nn.git
export TCNN_CUDA_ARCHITECTURES=86
cd tiny-cuda-nn/bindings/torch
python3 setup.py  install --user
# test by
python; import tinycudann as tcnn
```
