### ISSUE TITLE
Precision half leads to Nan

### ISSUE THREAD

**Issue by weihaosky** [NVlabs/tiny-cuda-nn#219]
Hi, I am using the tcnn.Network with network_config of 
```
{
                    "otype": "FullyFusedMLP",
                    "activation": "ReLU",
                    "output_activation": "Sigmoid",
                    "n_neurons": 64,
                    "n_hidden_layers": 2,
                }
```
But this sometimes leads to Nan outputs. This is caused by the float-16 precision. Could I turn the precision from torch.half to torch.float? Or how should I solve this?
Many thanks!

**Comment by Tom94** [comment]
Hi, if you want to use float-32 precision, tiny-cuda-nn will not be much faster (if at all) than `torch.Linear`. This is because the hardware matrix multipliers don't accelerate float-32 nearly as much as float-16, shifting the bottleneck towards computation rather than memory.

Long story short: if you need float-32, simply use torch's own neural networks and use `tcnn` only for its encodings.

**Comment by chauncy-hw** [comment]
I'm also having this problem, do you have any better solution at the moment？

**Comment by weihaosky** [comment]
> Hi, if you want to use float-32 precision, tiny-cuda-nn will not be much faster (if at all) than `torch.Linear`. This is because the hardware matrix multipliers don't accelerate float-32 nearly as much as float-16, shifting the bottleneck towards computation rather than memory.
> 
> Long story short: if you need float-32, simply use torch's own neural networks and use `tcnn` only for its encodings (which _do_ support `dtype=float32`).

Thanks for the reply. Could I just use the float-32 precision occasionally？e.g., when the input is large (or nan is detected), switch from float-16 to float-32 ?

**Comment by Tom94** [comment]
Automatic switching doesn't work particularly well in practice, because if one inputs requires fp-32 to not produce NaNs, most other inputs likely need the same (due to the MLP being fully connected). And then the automatic switch simply always picks fp-32 and you'd have been better off going with fp-32 from the start.

Numeric problems that cause NaNs at fp-16 are usually a symptom of a deeper issue in the optimization (e.g. weights flying off to near-zero or near-infinity) that would be good to suppress in general. My personal go-to approach is to apply a weak L2 regularization on the MLP parameters (weak as in `lambda = 1e-6` -- simply pick the lowest number of 10 that gets rid of the NaNs).

**Comment by jingyibo123** [comment]
For anyone who might face a smillar problem.

Adding a weak regularization on the paremeters does alleviate/postpone the NaN problem, at the cost of slower convergence.

In my case the real issue is a NaN gradiant in the tcnn MLP, which is solved by using AMSGrad.

Thanks for the great insight, @Tom94

**Comment by NagabhushanSN95** [comment]
Using tcnn with float32 could still be useful when modifying legacy code - without significant modifications. Is there a way to configure the tcnn to use float32 instead of float16?

**Comment by Tom94** [comment]
Yes, in `include/tiny-cuda-nn/common.h`, change the line
```cpp
#define TCNN_HALF_PRECISION (!(TCNN_MIN_GPU_ARCH == 61 || TCNN_MIN_GPU_ARCH <= 52))
```
to
```cpp
#define TCNN_HALF_PRECISION 1
```
and recompile.

**Comment by NagabhushanSN95** [comment]
Thanks. Is it not possible to do this without recompiling?

**Comment by Tom94** [comment]
No, it is not
