### ISSUE TITLE
Why does the fully fused MLP use a skew?

### ISSUE THREAD

**Issue by VasuAgrawal** [NVlabs/tiny-cuda-nn#55]
Hi,

I was just reading through the code in `fully_fused_mlp.cu` to try to better understand what makes tiny-cuda-nn so fast. The overall approach makes sense to me, with a single thread block handling 128 rows of the input batch (computed 16 rows at a time), and each warp within that thread block performing the multiplication with one column of the layer weights. However, I see that when shared memory is used (either to store the first layer's weights, or to store the intermediate activations), there's a `SKEW` parameter that gets used to stride the data. From what I can tell, when the feature size is a multiple of 16, this makes the data go from being densely packed to having 2 empty `__half` after each 8 `__half` value, increasing the shared memory usage by 25%. I wasn't able to find a place where the empty `__half` values get used, so I'm posting this issue to ask what the `SKEW` parameter is there for. My guess is that it's something related to the performance optimizations for tiny-cuda-nn, but if that's the case I'm not sure why this helps. I'd appreciate any explanation you could provide :).

Thanks for the wonderful library!

**Comment by Tom94** [comment]
Hi there, thanks for the kind words!

The answer lies in the way shared memory works: it is organized into "banks" that can be accessed in parallel. If multiple threads try to read shared memory from the _same_ bank, that access gets serialized. ([called a bank conflict; more info here](https://stackoverflow.com/questions/3841877/what-is-a-bank-conflict-doing-cuda-opencl-programming))

Adding the skew to the way data is laid out avoids a pathological memory access pattern that would otherwise have many of these bank conflicts.

Related: I believe there's a slightly better way to avoid these bank conflicts without using any extra memory at all -- the [CUTLASS library](https://github.com/NVIDIA/cutlass) uses bitwise operations to structure the order of memory access (I may be wrong, but I think they mention it in [this talk](https://developer.nvidia.com/gtc/2020/video/s21745-vid)) -- but on all the GPUs that were relevant to us so far, saving that little bit of shared memory wound up not making a difference.
